version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - webnet
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=attendance_system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: attendance_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - webnet
    depends_on:
      - db

networks:
  webnet:

volumes:
  db_data:
